allowBuilds:
  "@google/genai": true
  "@openrouter/sdk": true
  "@prisma/engines": true
  esbuild: true
  msgpackr-extract: true
  msw: true
  prisma: true
  protobufjs: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - shadcn@4.9.0
  - '@tanstack/ai-client@0.16.2 || 0.18.2'
  - '@tanstack/ai-event-client@0.5.3 || 0.6.5'
  - '@tanstack/ai-gemini@0.15.0 || 0.17.2'
  - '@tanstack/ai-groq@0.4.0 || 0.4.10'
  - '@tanstack/ai-ollama@0.8.0 || 0.8.7'
  - '@tanstack/ai-openrouter@0.13.0 || 0.14.2'
  - '@tanstack/ai-react@0.15.3 || 0.15.11'
  - '@tanstack/ai@0.27.0 || 0.34.0'
  - '@tanstack/openai-base@0.7.0 || 0.9.0'
  - '@tanstack/ai-devtools-core@0.4.7 || 0.4.14'
  - '@tanstack/react-ai-devtools@0.2.50 || 0.2.57'
  - cnfast@0.0.8
  - '@tanstack/ai-utils@0.3.0'
  - vite@8.1.0
  - '@tanstack/db@0.6.10'
  - '@tanstack/query-core@5.101.1'
  - '@tanstack/query-db-collection@1.0.42'
  - '@tanstack/query-devtools@5.101.1'
  - '@tanstack/react-query-devtools@5.101.1'
  - '@tanstack/react-query@5.101.1'
