/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as GeneralRouteRouteImport } from './routes/_general/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardImportRouteImport } from './routes/dashboard/import'
import { Route as DashboardDiscoverRouteImport } from './routes/dashboard/discover'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as DashboardItemsIndexRouteImport } from './routes/dashboard/items/index'
import { Route as DashboardDiariesIndexRouteImport } from './routes/dashboard/diaries/index'
import { Route as GeneralJournalIndexRouteImport } from './routes/_general/journal/index'
import { Route as GeneralBlogIndexRouteImport } from './routes/_general/blog/index'
import { Route as GeneralAboutIndexRouteImport } from './routes/_general/about/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as DashboardItemsItemIdRouteImport } from './routes/dashboard/items/$itemId'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiSummaryRouteImport } from './routes/api/ai/summary'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralRouteRoute = GeneralRouteRouteImport.update({
  id: '/_general',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardImportRoute = DashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDiscoverRoute = DashboardDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardItemsIndexRoute = DashboardItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDiariesIndexRoute = DashboardDiariesIndexRouteImport.update({
  id: '/diaries/',
  path: '/diaries/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const GeneralJournalIndexRoute = GeneralJournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => GeneralRouteRoute,
} as any)
const GeneralBlogIndexRoute = GeneralBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => GeneralRouteRoute,
} as any)
const GeneralAboutIndexRoute = GeneralAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => GeneralRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardItemsItemIdRoute = DashboardItemsItemIdRouteImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSummaryRoute = ApiAiSummaryRouteImport.update({
  id: '/api/ai/summary',
  path: '/api/ai/summary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/ai/summary': typeof ApiAiSummaryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/items/$itemId': typeof DashboardItemsItemIdRoute
  '/login/': typeof AuthLoginIndexRoute
  '/about/': typeof GeneralAboutIndexRoute
  '/blog/': typeof GeneralBlogIndexRoute
  '/journal/': typeof GeneralJournalIndexRoute
  '/dashboard/diaries/': typeof DashboardDiariesIndexRoute
  '/dashboard/items/': typeof DashboardItemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/ai/summary': typeof ApiAiSummaryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/items/$itemId': typeof DashboardItemsItemIdRoute
  '/login': typeof AuthLoginIndexRoute
  '/about': typeof GeneralAboutIndexRoute
  '/blog': typeof GeneralBlogIndexRoute
  '/journal': typeof GeneralJournalIndexRoute
  '/dashboard/diaries': typeof DashboardDiariesIndexRoute
  '/dashboard/items': typeof DashboardItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_general': typeof GeneralRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/ai/summary': typeof ApiAiSummaryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/items/$itemId': typeof DashboardItemsItemIdRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_general/about/': typeof GeneralAboutIndexRoute
  '/_general/blog/': typeof GeneralBlogIndexRoute
  '/_general/journal/': typeof GeneralJournalIndexRoute
  '/dashboard/diaries/': typeof DashboardDiariesIndexRoute
  '/dashboard/items/': typeof DashboardItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/$'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/api/ai/summary'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/items/$itemId'
    | '/login/'
    | '/about/'
    | '/blog/'
    | '/journal/'
    | '/dashboard/diaries/'
    | '/dashboard/items/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/profile'
    | '/dashboard'
    | '/api/ai/summary'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/items/$itemId'
    | '/login'
    | '/about'
    | '/blog'
    | '/journal'
    | '/dashboard/diaries'
    | '/dashboard/items'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_general'
    | '/dashboard'
    | '/api/$'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/api/ai/summary'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/items/$itemId'
    | '/_auth/login/'
    | '/_general/about/'
    | '/_general/blog/'
    | '/_general/journal/'
    | '/dashboard/diaries/'
    | '/dashboard/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GeneralRouteRoute: typeof GeneralRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAiSummaryRoute: typeof ApiAiSummaryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_general': {
      id: '/_general'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GeneralRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/import': {
      id: '/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof DashboardImportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/discover': {
      id: '/dashboard/discover'
      path: '/discover'
      fullPath: '/dashboard/discover'
      preLoaderRoute: typeof DashboardDiscoverRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/items/': {
      id: '/dashboard/items/'
      path: '/items'
      fullPath: '/dashboard/items/'
      preLoaderRoute: typeof DashboardItemsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/diaries/': {
      id: '/dashboard/diaries/'
      path: '/diaries'
      fullPath: '/dashboard/diaries/'
      preLoaderRoute: typeof DashboardDiariesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_general/journal/': {
      id: '/_general/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof GeneralJournalIndexRouteImport
      parentRoute: typeof GeneralRouteRoute
    }
    '/_general/blog/': {
      id: '/_general/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof GeneralBlogIndexRouteImport
      parentRoute: typeof GeneralRouteRoute
    }
    '/_general/about/': {
      id: '/_general/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof GeneralAboutIndexRouteImport
      parentRoute: typeof GeneralRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/items/$itemId': {
      id: '/dashboard/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/dashboard/items/$itemId'
      preLoaderRoute: typeof DashboardItemsItemIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/summary': {
      id: '/api/ai/summary'
      path: '/api/ai/summary'
      fullPath: '/api/ai/summary'
      preLoaderRoute: typeof ApiAiSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GeneralRouteRouteChildren {
  GeneralAboutIndexRoute: typeof GeneralAboutIndexRoute
  GeneralBlogIndexRoute: typeof GeneralBlogIndexRoute
  GeneralJournalIndexRoute: typeof GeneralJournalIndexRoute
}

const GeneralRouteRouteChildren: GeneralRouteRouteChildren = {
  GeneralAboutIndexRoute: GeneralAboutIndexRoute,
  GeneralBlogIndexRoute: GeneralBlogIndexRoute,
  GeneralJournalIndexRoute: GeneralJournalIndexRoute,
}

const GeneralRouteRouteWithChildren = GeneralRouteRoute._addFileChildren(
  GeneralRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardDiscoverRoute: typeof DashboardDiscoverRoute
  DashboardImportRoute: typeof DashboardImportRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardItemsItemIdRoute: typeof DashboardItemsItemIdRoute
  DashboardDiariesIndexRoute: typeof DashboardDiariesIndexRoute
  DashboardItemsIndexRoute: typeof DashboardItemsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDiscoverRoute: DashboardDiscoverRoute,
  DashboardImportRoute: DashboardImportRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardItemsItemIdRoute: DashboardItemsItemIdRoute,
  DashboardDiariesIndexRoute: DashboardDiariesIndexRoute,
  DashboardItemsIndexRoute: DashboardItemsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GeneralRouteRoute: GeneralRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiAiSummaryRoute: ApiAiSummaryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
