/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as GeneralRouteRouteImport } from './routes/_general/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardImportRouteImport } from './routes/dashboard/import'
import { Route as DashboardDiscoverRouteImport } from './routes/dashboard/discover'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as DashboardTaskTrackerIndexRouteImport } from './routes/dashboard/task-tracker/index'
import { Route as DashboardQuranTrackerIndexRouteImport } from './routes/dashboard/quran-tracker/index'
import { Route as DashboardItemsIndexRouteImport } from './routes/dashboard/items/index'
import { Route as DashboardBlogIndexRouteImport } from './routes/dashboard/blog/index'
import { Route as GeneralBlogIndexRouteImport } from './routes/_general/blog/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as DashboardTaskTrackerTaskListIdRouteImport } from './routes/dashboard/task-tracker/$taskListId'
import { Route as DashboardItemsItemIdRouteImport } from './routes/dashboard/items/$itemId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiSummaryRouteImport } from './routes/api/ai/summary'
import { Route as GeneralBlogSlugRouteImport } from './routes/_general/blog/$slug'
import { Route as DashboardBlogCreateBlogIndexRouteImport } from './routes/dashboard/blog/create-blog/index'
import { Route as DashboardBlogSlugIndexRouteImport } from './routes/dashboard/blog/$slug.index'
import { Route as DashboardBlogSlugEditRouteImport } from './routes/dashboard/blog/$slug.edit'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralRouteRoute = GeneralRouteRouteImport.update({
  id: '/_general',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardImportRoute = DashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDiscoverRoute = DashboardDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTaskTrackerIndexRoute =
  DashboardTaskTrackerIndexRouteImport.update({
    id: '/task-tracker/',
    path: '/task-tracker/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardQuranTrackerIndexRoute =
  DashboardQuranTrackerIndexRouteImport.update({
    id: '/quran-tracker/',
    path: '/quran-tracker/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardItemsIndexRoute = DashboardItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBlogIndexRoute = DashboardBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const GeneralBlogIndexRoute = GeneralBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => GeneralRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardTaskTrackerTaskListIdRoute =
  DashboardTaskTrackerTaskListIdRouteImport.update({
    id: '/task-tracker/$taskListId',
    path: '/task-tracker/$taskListId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardItemsItemIdRoute = DashboardItemsItemIdRouteImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSummaryRoute = ApiAiSummaryRouteImport.update({
  id: '/api/ai/summary',
  path: '/api/ai/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralBlogSlugRoute = GeneralBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => GeneralRouteRoute,
} as any)
const DashboardBlogCreateBlogIndexRoute =
  DashboardBlogCreateBlogIndexRouteImport.update({
    id: '/blog/create-blog/',
    path: '/blog/create-blog/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBlogSlugIndexRoute = DashboardBlogSlugIndexRouteImport.update({
  id: '/blog/$slug/',
  path: '/blog/$slug/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBlogSlugEditRoute = DashboardBlogSlugEditRouteImport.update({
  id: '/blog/$slug/edit',
  path: '/blog/$slug/edit',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/blog/$slug': typeof GeneralBlogSlugRoute
  '/api/ai/summary': typeof ApiAiSummaryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/items/$itemId': typeof DashboardItemsItemIdRoute
  '/dashboard/task-tracker/$taskListId': typeof DashboardTaskTrackerTaskListIdRoute
  '/login/': typeof AuthLoginIndexRoute
  '/blog/': typeof GeneralBlogIndexRoute
  '/dashboard/blog/': typeof DashboardBlogIndexRoute
  '/dashboard/items/': typeof DashboardItemsIndexRoute
  '/dashboard/quran-tracker/': typeof DashboardQuranTrackerIndexRoute
  '/dashboard/task-tracker/': typeof DashboardTaskTrackerIndexRoute
  '/dashboard/blog/$slug/edit': typeof DashboardBlogSlugEditRoute
  '/dashboard/blog/$slug/': typeof DashboardBlogSlugIndexRoute
  '/dashboard/blog/create-blog/': typeof DashboardBlogCreateBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/blog/$slug': typeof GeneralBlogSlugRoute
  '/api/ai/summary': typeof ApiAiSummaryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/items/$itemId': typeof DashboardItemsItemIdRoute
  '/dashboard/task-tracker/$taskListId': typeof DashboardTaskTrackerTaskListIdRoute
  '/login': typeof AuthLoginIndexRoute
  '/blog': typeof GeneralBlogIndexRoute
  '/dashboard/blog': typeof DashboardBlogIndexRoute
  '/dashboard/items': typeof DashboardItemsIndexRoute
  '/dashboard/quran-tracker': typeof DashboardQuranTrackerIndexRoute
  '/dashboard/task-tracker': typeof DashboardTaskTrackerIndexRoute
  '/dashboard/blog/$slug/edit': typeof DashboardBlogSlugEditRoute
  '/dashboard/blog/$slug': typeof DashboardBlogSlugIndexRoute
  '/dashboard/blog/create-blog': typeof DashboardBlogCreateBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_general': typeof GeneralRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_general/blog/$slug': typeof GeneralBlogSlugRoute
  '/api/ai/summary': typeof ApiAiSummaryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/items/$itemId': typeof DashboardItemsItemIdRoute
  '/dashboard/task-tracker/$taskListId': typeof DashboardTaskTrackerTaskListIdRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_general/blog/': typeof GeneralBlogIndexRoute
  '/dashboard/blog/': typeof DashboardBlogIndexRoute
  '/dashboard/items/': typeof DashboardItemsIndexRoute
  '/dashboard/quran-tracker/': typeof DashboardQuranTrackerIndexRoute
  '/dashboard/task-tracker/': typeof DashboardTaskTrackerIndexRoute
  '/dashboard/blog/$slug/edit': typeof DashboardBlogSlugEditRoute
  '/dashboard/blog/$slug/': typeof DashboardBlogSlugIndexRoute
  '/dashboard/blog/create-blog/': typeof DashboardBlogCreateBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/$'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/blog/$slug'
    | '/api/ai/summary'
    | '/api/auth/$'
    | '/dashboard/items/$itemId'
    | '/dashboard/task-tracker/$taskListId'
    | '/login/'
    | '/blog/'
    | '/dashboard/blog/'
    | '/dashboard/items/'
    | '/dashboard/quran-tracker/'
    | '/dashboard/task-tracker/'
    | '/dashboard/blog/$slug/edit'
    | '/dashboard/blog/$slug/'
    | '/dashboard/blog/create-blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/profile'
    | '/dashboard'
    | '/blog/$slug'
    | '/api/ai/summary'
    | '/api/auth/$'
    | '/dashboard/items/$itemId'
    | '/dashboard/task-tracker/$taskListId'
    | '/login'
    | '/blog'
    | '/dashboard/blog'
    | '/dashboard/items'
    | '/dashboard/quran-tracker'
    | '/dashboard/task-tracker'
    | '/dashboard/blog/$slug/edit'
    | '/dashboard/blog/$slug'
    | '/dashboard/blog/create-blog'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_general'
    | '/dashboard'
    | '/api/$'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/_general/blog/$slug'
    | '/api/ai/summary'
    | '/api/auth/$'
    | '/dashboard/items/$itemId'
    | '/dashboard/task-tracker/$taskListId'
    | '/_auth/login/'
    | '/_general/blog/'
    | '/dashboard/blog/'
    | '/dashboard/items/'
    | '/dashboard/quran-tracker/'
    | '/dashboard/task-tracker/'
    | '/dashboard/blog/$slug/edit'
    | '/dashboard/blog/$slug/'
    | '/dashboard/blog/create-blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GeneralRouteRoute: typeof GeneralRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAiSummaryRoute: typeof ApiAiSummaryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_general': {
      id: '/_general'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GeneralRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/import': {
      id: '/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof DashboardImportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/discover': {
      id: '/dashboard/discover'
      path: '/discover'
      fullPath: '/dashboard/discover'
      preLoaderRoute: typeof DashboardDiscoverRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/task-tracker/': {
      id: '/dashboard/task-tracker/'
      path: '/task-tracker'
      fullPath: '/dashboard/task-tracker/'
      preLoaderRoute: typeof DashboardTaskTrackerIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/quran-tracker/': {
      id: '/dashboard/quran-tracker/'
      path: '/quran-tracker'
      fullPath: '/dashboard/quran-tracker/'
      preLoaderRoute: typeof DashboardQuranTrackerIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/items/': {
      id: '/dashboard/items/'
      path: '/items'
      fullPath: '/dashboard/items/'
      preLoaderRoute: typeof DashboardItemsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/blog/': {
      id: '/dashboard/blog/'
      path: '/blog'
      fullPath: '/dashboard/blog/'
      preLoaderRoute: typeof DashboardBlogIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_general/blog/': {
      id: '/_general/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof GeneralBlogIndexRouteImport
      parentRoute: typeof GeneralRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/task-tracker/$taskListId': {
      id: '/dashboard/task-tracker/$taskListId'
      path: '/task-tracker/$taskListId'
      fullPath: '/dashboard/task-tracker/$taskListId'
      preLoaderRoute: typeof DashboardTaskTrackerTaskListIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/items/$itemId': {
      id: '/dashboard/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/dashboard/items/$itemId'
      preLoaderRoute: typeof DashboardItemsItemIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/summary': {
      id: '/api/ai/summary'
      path: '/api/ai/summary'
      fullPath: '/api/ai/summary'
      preLoaderRoute: typeof ApiAiSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_general/blog/$slug': {
      id: '/_general/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof GeneralBlogSlugRouteImport
      parentRoute: typeof GeneralRouteRoute
    }
    '/dashboard/blog/create-blog/': {
      id: '/dashboard/blog/create-blog/'
      path: '/blog/create-blog'
      fullPath: '/dashboard/blog/create-blog/'
      preLoaderRoute: typeof DashboardBlogCreateBlogIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/blog/$slug/': {
      id: '/dashboard/blog/$slug/'
      path: '/blog/$slug'
      fullPath: '/dashboard/blog/$slug/'
      preLoaderRoute: typeof DashboardBlogSlugIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/blog/$slug/edit': {
      id: '/dashboard/blog/$slug/edit'
      path: '/blog/$slug/edit'
      fullPath: '/dashboard/blog/$slug/edit'
      preLoaderRoute: typeof DashboardBlogSlugEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GeneralRouteRouteChildren {
  GeneralBlogSlugRoute: typeof GeneralBlogSlugRoute
  GeneralBlogIndexRoute: typeof GeneralBlogIndexRoute
}

const GeneralRouteRouteChildren: GeneralRouteRouteChildren = {
  GeneralBlogSlugRoute: GeneralBlogSlugRoute,
  GeneralBlogIndexRoute: GeneralBlogIndexRoute,
}

const GeneralRouteRouteWithChildren = GeneralRouteRoute._addFileChildren(
  GeneralRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardDiscoverRoute: typeof DashboardDiscoverRoute
  DashboardImportRoute: typeof DashboardImportRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardItemsItemIdRoute: typeof DashboardItemsItemIdRoute
  DashboardTaskTrackerTaskListIdRoute: typeof DashboardTaskTrackerTaskListIdRoute
  DashboardBlogIndexRoute: typeof DashboardBlogIndexRoute
  DashboardItemsIndexRoute: typeof DashboardItemsIndexRoute
  DashboardQuranTrackerIndexRoute: typeof DashboardQuranTrackerIndexRoute
  DashboardTaskTrackerIndexRoute: typeof DashboardTaskTrackerIndexRoute
  DashboardBlogSlugEditRoute: typeof DashboardBlogSlugEditRoute
  DashboardBlogSlugIndexRoute: typeof DashboardBlogSlugIndexRoute
  DashboardBlogCreateBlogIndexRoute: typeof DashboardBlogCreateBlogIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDiscoverRoute: DashboardDiscoverRoute,
  DashboardImportRoute: DashboardImportRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardItemsItemIdRoute: DashboardItemsItemIdRoute,
  DashboardTaskTrackerTaskListIdRoute: DashboardTaskTrackerTaskListIdRoute,
  DashboardBlogIndexRoute: DashboardBlogIndexRoute,
  DashboardItemsIndexRoute: DashboardItemsIndexRoute,
  DashboardQuranTrackerIndexRoute: DashboardQuranTrackerIndexRoute,
  DashboardTaskTrackerIndexRoute: DashboardTaskTrackerIndexRoute,
  DashboardBlogSlugEditRoute: DashboardBlogSlugEditRoute,
  DashboardBlogSlugIndexRoute: DashboardBlogSlugIndexRoute,
  DashboardBlogCreateBlogIndexRoute: DashboardBlogCreateBlogIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GeneralRouteRoute: GeneralRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiAiSummaryRoute: ApiAiSummaryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
